services:
  traefik:
    image: traefik:v3.7.5
    container_name: traefik

    restart: unless-stopped

    env_file:
      - .env

    environment:
      TZ: ${TZ}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}

    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_HTTPS_PORT}:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - /home/kifu/data/traefik/letsencrypt:/letsencrypt

  cloudflared:
    image: cloudflare/cloudflared:2026.6.1
    container_name: cloudflared

    restart: unless-stopped

    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${CF_TUNNEL_TOKEN}

    networks:
      - gateway
