global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

ping: {}

entryPoints:
  web:
    address: ":80"
    # Không redirect HTTP→HTTPS ở đây vì traffic đến qua Cloudflare Tunnel
    # Cloudflare đã xử lý HTTPS, tunnel forward vào Traefik qua HTTP nội bộ

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "nextchat.vn"
            sans:
              - "*.nextchat.vn"

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true

  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: kifu.dev@gmail.com
      storage: /letsencrypt/acme.json

      dnsChallenge:
        provider: cloudflare

log:
  level: INFO

accessLog: {}
