# zone                 hostname                  proxied

nextchat.vn            traefik.nextchat.vn       false

# nextchat.vn          nextchat.vn               false
# nextchat.vn          meet.nextchat.vn          true
# nextchat.vn          secrets.nextchat.vn       true
# nextchat.vn          s3.nextchat.vn            true

# kifu.id.vn           home.kifu.id.vn           false
# kifu.id.vn           portainer.kifu.id.vn      false
# kifu.id.vn           npm.kifu.id.vn            false